JSON configuration manager

diff --git a/cameraTestStreamCameraModule b/cameraTestStreamCameraModule
--- a/cameraTestStreamCameraModule
+++ b/cameraTestStreamCameraModule
@@ -6,4 +6,14 @@ echo "Go to "
 	listecho $(ipAddress)":8080"
 messagebox "Press CTRL-C to stop the test"
 console
-/opt/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -o "/opt/mjpg-streamer/mjpg-streamer-experimental/output_http.so -w /usr/www" -i "input_raspicam.so -fps 10 -quality 5"
+allargs=$("/opt/piget/camera/python/readCameraJson.py")
+
+#http://unix.stackexchange.com/questions/163898/how-to-assign-a-string-value-to-a-variable-over-multiple-lines-while-indented
+outputArgs=$(echo "${allargs//   /}"|head -n1)
+inputArgs=$(echo "${allargs//   /}"|tail -n -1)
+
+if [ $? -eq 0 ];then
+	/opt/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -o "/opt/mjpg-streamer/mjpg-streamer-experimental/output_http.so -w /usr/www $outputArgs" -i "input_raspicam.so $inputArgs"
+else
+	echo "ERROR IN CONFIG FILE: $args"
+fi
